### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcrystal#1]
In order to launch we should have:

- [x] Crystal as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] At least 10 problems
- [x] Documentation (see below)
- [x] One to a handful of people willing to check exercism regularly (daily?) to review. This will ensure that the track gets off on the right foot.
- [x] Add track implementors and other designated code reviewers as mentors to the track. This gives you access to all the solutions in Crystal whether or not you've submitted the problem to the site.
- [x] Add a language icon or logo (see below)
- [x] Toggle `"active"` to `true` in `config.json`
- [x] Send an email to the mailing list.

## Documentation

The documentation lives in the `docs/` directory here in this repository, and gets served to the site via the x-api. It should contain at minimim:

- `INSTALLATION.md` - about how to get the language set up locally.
- `TESTS.md` - about how to run the tests for the exercises.

Some nice to haves:

- `ABOUT.md` - a short, friendly blurb about the language. What types of problems does it solve really well? What is it typically used for?
- `LEARNING.md` - a few notes about where people might want to go to learn the language from scratch.
- `RESOURCES.md` - references and other useful resources.

## Logo/Icon

We try to create a language icon that has the exercism colors, and is recognizably similar to the language icon. Sometimes this isn't possible due to copyright issues. See http://exercism.io/languages for all the existing icons.

The logo should live under `/public/img/tracks/` in the exercism/exercism.io repository.
https://github.com/exercism/exercism.io/tree/master/public/img/tracks

Attribution goes in https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md

If image assets are not your strong suit, just find a reasonable image to start from, along with the information about the licensing, and we'll figure out the colorization thing (I've written some scripts to help me do this part).

Some icons are the official language logo (tweaked). Where a language doesn't seem to have an official logo, or where the official logo has copyright issues, we just make something up.

## Successful Launches

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by mhelmetag** [comment]
Not exactly sure how long this will take but I'll chip away at these. Thanks for setting this up!!

**Comment by kytrinyx** [comment]
Yeah, no hurry--we've got a bunch of tracks that are in the "might be launched someday" category.

**Comment by mhelmetag** [comment]
How do I get xcrystal to get picked up by travis?

**Comment by kytrinyx** [comment]
Oh, I have to turn that on. Just a sec.

**Comment by kytrinyx** [comment]
Done.

**Comment by mhelmetag** [comment]
Sweet!! Thanks :)

**Comment by elorest** [comment]
I would be fine to be on the list for "Add track implementors and other designated code reviewers as mentors to the track", if you need anyone.

**Comment by mhelmetag** [comment]
@elorest, we definitely do. Once we set the language to active, we can pair on whatever exercises get posted on exercism.

**Comment by tejasbubane** [comment]
Can we get the list updated? I guess we have 10 exercises now. Any more things left for launching?

**Comment by kytrinyx** [comment]
Sweet! I've added @mhelmetag and @elorest as track mentors. Anyone else that I should add here?

**Comment by mhelmetag** [comment]
@kytrinyx , I think that's it for now... unless I'm missing something. It looks like @gangwolf is itching to get this track active 😄  so does anyone disagree with starting up Crystal this weekend?

**Comment by kytrinyx** [comment]
Let's do it!

**Comment by elorest** [comment]
Lets.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by mhelmetag** [comment]
Flag set to active! Thanks, @Gangwolf !

**Comment by kytrinyx** [comment]
Deploying this now! I'll announce it in the newsletter (and on twitter) today.
